version: '3.2'
services:
  blaze:
    image: "samply/blaze:0.15"
    environment:
      BASE_URL: "http://blaze:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      LOG_LEVEL: "debug"
    ports:
      - "8090:8080"
      - "8091:8081"
    volumes:
      - "blaze-data:/app/data"

  dktk-fed-search-share:
    build: .
    environment:
      APP_BASE_URL: "http://dktk-fed-search-share:8080"
      APP_STORE_URL: "http://blaze:8080/fhir"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
    ports:
      - "8080:8080"
    depends_on:
      - blaze

volumes:
  blaze-data:
