app:
  broker:
    baseUrl: http://localhost:8090/broker/rest/searchbroker
    authToken: foo
    mail: foo
  store:
    baseUrl: http://localhost:8100/fhir
    # increase this depending on the longest running CQL queries
    socketTimeout: 60000
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
