app:
  broker:
    baseUrl: http://localhost:8090/broker/rest/searchbroker
    authToken: foo
  store:
    baseUrl: http://localhost:8100/fhir
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
