app:
  broker:
    baseUrl: http://localhost:8090/broker/rest/searchbroker
    authToken: foo
    mail: foo
  store:
    baseUrl: http://localhost:8100/fhir
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dktk-fed-search-share
    username: dktk-fed-search-share
    password: dktk-fed-search-share
  sql:
    init:
      mode: always
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
